### ISSUE TITLE
What is this? There's no README

### ISSUE THREAD

**Issue by jcansdale** [jcansdale/DogfoodVsix#3]
### What is Dogfood.vsix?

Dogfood.vsix is what you use when your extension is ready to try in your main Visual Studio 2015 or 2017 instance.

![image](https://user-images.githubusercontent.com/11719160/41686244-441010b6-74db-11e8-809c-a8e4b1c2acdb.png)

It does a few things to make this process as painless as possible.

1. If your current solution contains an extension project, it will locate the .vsix and suggest opening it
2. You're free choose a different one or paste in a .vsix URL to open (e.g. from a releases page)
3. If the extension is already installed, it will be uninstalled (even if it's a newer version)
4. All users extensions will be tweaked to install for the current user (so you don't need to close all `devenv.exe` processes)
5. The name of the extension will have `[Dogfood]` added so you know it's *special*
6. Your extension's install directory and assets will be displayed on the output window

![image](https://user-images.githubusercontent.com/11719160/41687045-42cafb28-74de-11e8-805c-17c528c7a4c6.png)

Restart Visual Studio and start dogfooding! 🍽 

You can find the latest `Dogfood.vsix` here:
http://vsixgallery.com/extension/Dogfood.2f4d62f7-a328-4604-840d-0472b058edcd/

### Does that make sense?

Please add any questions or suggestions in the comments. I'll then add a long overdue `README.md`. 😉

**Comment by madskristensen** [comment]
It is not clear to me:

* How this is different from launching the Experimental Instance using F5 in VS
* What problem this extension solves
* Why I should use it

**Comment by ironcev** [comment]
@madskristensen After evaluating Dogfood.vsix thoroughly, my answers to your questions are below:

Ad 1) How this is different from launching the Experimental Instance using F5 in VS

F5 in VS runs Experimental VS Instance *under the debugger*. Means, it slows down the Experimental Instance noticeably. **F5 is fine if we really need to debug and develop, but not if we want to try/dogfood our extension, especially if it is resource intensive one.**

To the rescue, we can also press Ctrl+F5 and start the Experimental Instance without the debugger attached. E.g., in my standard setup, pressing F5 takes 45 seconds until I get my moderate Smoke Tests solution loaded in Experimental VS. Pressing Ctrl+F5 takes only 30 seconds. When loading a solution of realistic size, the difference is even more significant. When my extension runs static code analysis on a whole solution, there is a noticeable time difference doing that with the debugger attached and without.

So, using F5 to dogfood can be painful concerning waiting time. The question is, is there any difference between Ctrl+F5/Experimental Instance vs. Dogfood.vsix? In terms of time delay, no. **To load the extension with Dogfood.vsix, restart VS, and reload it to the previous state takes roughly the same amount of time as starting the Experimental Instance without the debugger attached.**

The only noticeable difference is that in the main instance we will have all other extensions installed, etc., basically our usual VS setup. In case this is relevant for dogfooding I see having the "more realistic" environment as a benefit, but not a significant one.

Still, I find the extension very useful in another one important scenario, explained below.

Ad 2) What problem this extension solves
**Paradoxically I see Dogfood.vsix as beneficial not so much for the authors of extensions, but for those who want to try-out someone's extensions ;-)**

Here are two concrete, real-life uses cases.

When my release candidate is ready, I invite for [Running the Endgame event](https://github.com/sharpenrocks/Sharpen/wiki/Running-the-Endgame) event, essentially, beta testing. I try to keep it simple for the Runners so that testing does not take much of their time. Still, Runners rarely start kicking in immediately. The feedback I got from most of them is that **they are reluctant to try it out immediately because they first have to close all the running VS instances they have, and that's painful**.

Practically, this is a huge issue. @madskristensen I listened to your talk at .NET Rocks Podcast, and I'm rooting for you with all my heart and looking forward to everything you are up to change and improve, especially the discoverability of extensions. But that's only a half of equation. **If one needs to restart all the instances of VS to quickly try out some extension that might be helpful, the acceptance of VS extensions will always remain low**, I'm sure about that. Most of the developers I am daily in touch have at least two VS instances open containing complex solutions that take time to load, ReSharper, ...

Restarting *all* VS instances is something one does only when it's absolutely necessary.

Second use case, in its essence same as the first one. As an extension developer, I love to try-out other extensions available on the VS marketplace or VsixGallery. But I don't do it as often as I would like to. Why? Because on average I run 5 Windows desktops in parallel and on each of them at least two instances of VS. Shutting down and restarting all that just to try out some cute tiny extension? Phew. No way.

Dogfood.vsix suddenly solves me these two issues :-)

I'll tell Sharpen Endgame Runners to install Dogfood.vsix an install Sharpen through it directly from the provided link. They'll still have to restart a single VS instance, but that's acceptable.

I can now experiment more with extensions available in the wild. Again, restarting each time only one VS instance, but I can live with that.

Ad 3) Why I should use it
**To install and play with VS extensions without the need to restart all instances of VS. At least until VS start supporting this vital feature on its own.**

@madskristensen Please let me know if I'm missing something. Maybe there is a way to achieve the same with VSIX installer already, but I'm not aware of it. I was searching for possibilities to install VSIX-ex without restarting VS or at least without restarting all running instances. Everything I found was similar to [this](https://developercommunity.visualstudio.com/content/problem/36536/cannot-install-vsix-without-terminating-visual-stu.html) - not supported.

And please (re)think of supporting this in VS/VSIX installer. It will for sure have a positive impact on the acceptance of VS extensions ;-)

@jcansdale Please correct me if you think I didn't get the things right. And thanks for the extension! I already tried three "cute tiny extensions" while evaluating Dogfood.vsix. Restarting just one VS was a fair price to pay :-)

**Comment by ironcev** [comment]
@jcansdale The README.md is there, so I guess this issue can be closed :-)

But I think @madskristensen is right. You explained perfectly *what* the extension does and *how* but not *why* someone should be using it. The benefits of using it are not that clear.

Rewriting the README in the "Start with Why" spirit makes sense IMO. I could give it a try if you are ready to start getting contributions on Dogfood.vsix ;-)

**Comment by jcansdale** [comment]
> Rewriting the README in the "Start with Why" spirit makes sense IMO. I could give it a try if you are ready to start getting contributions on Dogfood.vsix ;-)

That would be very much appreciated! I suck at describing things, especially when I'm close/familiar with them. 😄

**Comment by ironcev** [comment]
:-) Ok, I'll give it a try. It will, unfortunately, have to wait until the weekend, same as all my open source contributions. Meanwhile, I'm sending a quick PR with a two-letter fix for a small typo in the current README ;-) Just as warmup :-)

**Comment by jcansdale** [comment]
It now has a readme so closing. 😄
